@extends('layouts.app')
@section('title', $variavel->exists ? 'Editar variável' : 'Nova variável')
@push('styles')
<link href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.6.2/cropper.min.css" rel="stylesheet">
<style>.image-drop{padding:2rem;border:2px dashed #adb5bd;border-radius:.75rem;background:#f8f9fa;text-align:center;cursor:pointer}.image-drop:hover{border-color:#0d6efd;background:#f2f7ff}.image-editor{max-height:28rem;background:#eef1f5}.image-editor img{display:block;max-width:100%}.image-result{max-width:100%;max-height:16rem;object-fit:contain}</style>
@endpush
@section('content')
@php($imageExists = $variavel->imageExists())
<div class="mb-4"><h1 class="page-title">{{ $variavel->exists?'Editar variável':'Nova variável' }}</h1><p class="page-description mb-0">Configure o conteúdo e o posicionamento da variável.</p></div>
<form id="variavelForm" method="POST" enctype="multipart/form-data" action="{{ $variavel->exists?route('variaveis.update',$variavel):route('variaveis.store') }}">@csrf @if($variavel->exists) @method('PUT') @endif
<div class="card content-card"><div class="card-header"><h2 class="h5 fw-bold mb-0">Dados da variável</h2></div><div class="card-body p-4">
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div id="editorAlert" class="alert alert-danger d-none"></div>
<div class="row g-3">
    <div class="col-12 col-md-5"><label for="nome" class="form-label">Nome da variável *</label><input id="nome" name="nome" class="form-control" maxlength="20" required value="{{ old('nome',$variavel->nome) }}"><div class="form-text">Até 20 caracteres.</div></div>
    <div class="col-12 col-md-4"><label for="tipo" class="form-label">Tipo *</label><select id="tipo" name="tipo" class="form-select" required><option value="">Selecione</option><option value="imagem" @selected(old('tipo',$variavel->tipo)==='imagem')>Imagem</option><option value="texto" @selected(old('tipo',$variavel->tipo)==='texto')>Texto</option></select></div>
    <div class="col-12 col-md-3"><label for="ativo" class="form-label">Status *</label><select id="ativo" name="ativo" class="form-select" required><option value="1" @selected((string)old('ativo',$variavel->exists?(int)$variavel->ativo:1)==='1')>Ativa</option><option value="0" @selected((string)old('ativo',$variavel->exists?(int)$variavel->ativo:1)==='0')>Inativa</option></select></div>

    <div id="imageFields" class="col-12 d-none"><label class="form-label">Imagem</label><input id="imagem" name="imagem" type="file" class="d-none" accept=".png,.jpg,.jpeg,image/png,image/jpeg"><input id="remover_imagem" name="remover_imagem" type="hidden" value="{{ old('remover_imagem',0) }}">
        @if($variavel->imagem&&!$imageExists)<div id="missingImage" class="alert alert-warning"><i class="bi bi-exclamation-triangle me-1"></i>O arquivo <strong>{{ $variavel->imagem }}</strong> não foi encontrado. Envie uma nova imagem.</div>@endif
        <div id="dropArea" class="image-drop {{ $imageExists?'d-none':'' }}" tabindex="0"><i class="bi bi-cloud-arrow-up fs-2 text-primary"></i><div class="fw-semibold mt-2">Clique para selecionar ou cole uma imagem aqui</div><div class="text-muted small">PNG, JPG ou JPEG, com até 10 MB</div></div>
        <div id="editorArea" class="{{ $imageExists?'':'d-none' }}"><div class="image-editor rounded border overflow-hidden"><img id="editorImage" @if($imageExists) src="{{ $variavel->imageUrl() }}" @endif alt="Editor da imagem"></div>
            <div class="d-flex flex-wrap align-items-end gap-2 mt-3"><button id="applyCrop" type="button" class="btn btn-outline-primary"><i class="bi bi-crop me-1"></i>Aplicar recorte</button><button id="removeBackground" type="button" class="btn btn-outline-secondary"><i class="bi bi-magic me-1"></i>Tentar remover fundo</button><div><label for="tolerance" class="form-label small mb-0">Tolerância do fundo: <span id="toleranceValue">45</span></label><input id="tolerance" type="range" class="form-range" min="10" max="120" value="45" style="width:180px"></div><button id="replaceImage" type="button" class="btn btn-outline-secondary"><i class="bi bi-arrow-repeat me-1"></i>Trocar imagem</button><button id="deleteImage" type="button" class="btn btn-outline-danger"><i class="bi bi-trash me-1"></i>Remover</button></div>
            <div class="form-text">A remoção usa a cor dos cantos como fundo. Ajuste a tolerância e tente novamente se necessário.</div><div id="processedArea" class="d-none mt-3"><div class="form-label fw-semibold">Resultado que será salvo</div><div class="border rounded bg-white p-2"><img id="processedImage" class="image-result" alt="Resultado processado"></div></div>
        </div>
    </div>

    <div id="textFields" class="col-12 d-none"><div class="row g-3"><div class="col-12"><label for="texto" class="form-label">Texto</label><textarea id="texto" name="texto" class="form-control text-only" rows="4">{{ old('texto',$variavel->texto) }}</textarea></div><div class="col-12 col-md-4"><label for="alinhamento" class="form-label">Alinhamento</label><select id="alinhamento" name="alinhamento" class="form-select text-only"><option value="">Selecione</option>@foreach(['esquerda'=>'Esquerda','direita'=>'Direita','centralizado'=>'Centralizado','justificado'=>'Justificado'] as $value=>$label)<option value="{{ $value }}" @selected(old('alinhamento',$variavel->alinhamento)===$value)>{{ $label }}</option>@endforeach</select></div><div class="col-12 col-md-4"><label for="cor" class="form-label">Cor</label><input id="cor" name="cor" class="form-control text-only" maxlength="15" placeholder="#000000" value="{{ old('cor',$variavel->cor) }}"></div></div></div>
    @foreach([['pos_x','Posição X'],['pox_y','Posição Y'],['altura','Altura'],['largura','Largura'],['centro_x','Centro X'],['centro_y','Centro Y']] as [$field,$label])<div class="col-6 col-md-2"><label for="{{ $field }}" class="form-label">{{ $label }}</label><input id="{{ $field }}" name="{{ $field }}" type="number" class="form-control" value="{{ old($field,$variavel->{$field}) }}" @if(in_array($field,['altura','largura'],true)) min="0" @endif></div>@endforeach
</div><div class="d-flex justify-content-end gap-2 mt-4"><a href="{{ route('variaveis.index') }}" class="btn btn-outline-secondary">Cancelar</a><button class="btn btn-primary"><i class="bi bi-check-lg me-1"></i>Salvar</button></div>
</div></div></form>
@endsection
@push('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.6.2/cropper.min.js"></script>
<script>
document.addEventListener('DOMContentLoaded',()=>{
 const form=document.getElementById('variavelForm'),tipo=document.getElementById('tipo'),imageFields=document.getElementById('imageFields'),textFields=document.getElementById('textFields'),input=document.getElementById('imagem'),drop=document.getElementById('dropArea'),editorArea=document.getElementById('editorArea'),image=document.getElementById('editorImage'),processedArea=document.getElementById('processedArea'),processed=document.getElementById('processedImage'),flag=document.getElementById('remover_imagem'),alertBox=document.getElementById('editorAlert'),tolerance=document.getElementById('tolerance'),toleranceValue=document.getElementById('toleranceValue'),missing=document.getElementById('missingImage');let cropper=null,objectUrl=null,processedUrl=null;
 const updateType=()=>{const isImage=tipo.value==='imagem';imageFields.classList.toggle('d-none',!isImage);textFields.classList.toggle('d-none',isImage);document.querySelectorAll('.text-only').forEach(field=>field.disabled=isImage)};tipo.addEventListener('change',updateType);updateType();
 const error=message=>{alertBox.textContent=message;alertBox.classList.remove('d-none')},clearError=()=>alertBox.classList.add('d-none');const destroyUrls=()=>{if(objectUrl)URL.revokeObjectURL(objectUrl);if(processedUrl)URL.revokeObjectURL(processedUrl);objectUrl=null;processedUrl=null};
 const initCropper=()=>{if(cropper)cropper.destroy();cropper=new Cropper(image,{viewMode:1,autoCropArea:1,background:false,responsive:true});editorArea.classList.remove('d-none');drop.classList.add('d-none')};if(image.getAttribute('src')){if(image.complete)initCropper();else image.addEventListener('load',initCropper,{once:true})}
 const loadFile=file=>{clearError();if(!['image/png','image/jpeg'].includes(file.type)&&!/[.](png|jpe?g)$/i.test(file.name)){error('Selecione uma imagem PNG, JPG ou JPEG.');return}if(file.size>10*1024*1024){error('A imagem deve ter no máximo 10 MB.');return}destroyUrls();objectUrl=URL.createObjectURL(file);image.onload=initCropper;image.src=objectUrl;processedArea.classList.add('d-none');flag.value='0';if(missing)missing.classList.add('d-none');const transfer=new DataTransfer();transfer.items.add(file);input.files=transfer.files};
 const exportImage=removeBg=>{if(!cropper)return;clearError();const canvas=cropper.getCroppedCanvas({imageSmoothingEnabled:true,imageSmoothingQuality:'high'});if(removeBg){const context=canvas.getContext('2d'),pixels=context.getImageData(0,0,canvas.width,canvas.height),data=pixels.data,corners=[[0,0],[canvas.width-1,0],[0,canvas.height-1],[canvas.width-1,canvas.height-1]],background=[0,0,0];corners.forEach(([x,y])=>{const i=(y*canvas.width+x)*4;background[0]+=data[i]/4;background[1]+=data[i+1]/4;background[2]+=data[i+2]/4});const limit=Number(tolerance.value);for(let i=0;i<data.length;i+=4){const distance=Math.sqrt((data[i]-background[0])**2+(data[i+1]-background[1])**2+(data[i+2]-background[2])**2);if(distance<=limit)data[i+3]=0;else if(distance<limit+25)data[i+3]=Math.round(data[i+3]*(distance-limit)/25)}context.putImageData(pixels,0,0)}canvas.toBlob(blob=>{if(!blob){error('Não foi possível processar a imagem.');return}if(blob.size>10*1024*1024){error('O resultado ultrapassa 10 MB. Faça um recorte menor.');return}if(processedUrl)URL.revokeObjectURL(processedUrl);processedUrl=URL.createObjectURL(blob);processed.src=processedUrl;processedArea.classList.remove('d-none');const file=new File([blob],'variavel.png',{type:'image/png'}),transfer=new DataTransfer();transfer.items.add(file);input.files=transfer.files;flag.value='0'},'image/png')};
 drop.addEventListener('click',()=>input.click());drop.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();input.click()}});document.getElementById('replaceImage').addEventListener('click',()=>input.click());input.addEventListener('change',()=>{if(input.files[0])loadFile(input.files[0])});document.addEventListener('paste',event=>{if(tipo.value!=='imagem')return;const file=[...event.clipboardData.items].find(item=>item.type.startsWith('image/'))?.getAsFile();if(file){event.preventDefault();loadFile(file)}});
 document.getElementById('applyCrop').addEventListener('click',()=>exportImage(false));document.getElementById('removeBackground').addEventListener('click',()=>exportImage(true));tolerance.addEventListener('input',()=>toleranceValue.textContent=tolerance.value);document.getElementById('deleteImage').addEventListener('click',()=>{if(cropper){cropper.destroy();cropper=null}destroyUrls();input.value='';image.removeAttribute('src');processed.removeAttribute('src');processedArea.classList.add('d-none');editorArea.classList.add('d-none');drop.classList.remove('d-none');flag.value='1';clearError()});
 form.addEventListener('submit',()=>{if(tipo.value!=='imagem')flag.value='1'});
});
</script>
@endpush
