@extends('layouts.app')
@section('title',$imagem->exists?'Editar imagem':'Nova imagem')
@push('styles')
<link href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.6.2/cropper.min.css" rel="stylesheet">
<style>.image-drop{padding:2rem;border:2px dashed #adb5bd;border-radius:.75rem;background:#f8f9fa;text-align:center;cursor:pointer}.image-drop:hover{border-color:#0d6efd;background:#f2f7ff}.image-editor{max-height:32rem;background:#eef1f5}.image-editor img{display:block;max-width:100%}.image-result{max-width:100%;max-height:20rem;object-fit:contain}.vector-preview{height:28rem;overflow:hidden;position:relative;background-color:#fff;background-image:linear-gradient(45deg,#e9ecef 25%,transparent 25%),linear-gradient(-45deg,#e9ecef 25%,transparent 25%),linear-gradient(45deg,transparent 75%,#e9ecef 75%),linear-gradient(-45deg,transparent 75%,#e9ecef 75%);background-size:20px 20px;background-position:0 0,0 10px,10px -10px,-10px 0;cursor:default}.vector-preview svg{width:100%;height:100%;display:block;transform-origin:center;user-select:none}.vector-preview svg path{cursor:pointer}.vector-preview svg path:hover,.vector-preview svg path.is-selected{filter:drop-shadow(0 0 2px #0d6efd);stroke:#0d6efd;stroke-width:1}.vector-color-panel{min-height:8rem}</style>
@endpush
@section('content')
<div class="mb-4"><h1 class="page-title">{{ $imagem->exists?'Editar imagem':'Nova imagem da biblioteca' }}</h1><p class="page-description mb-0">Recorte a imagem e, se necessário, remova o fundo antes de salvar.</p></div>
<form method="POST" enctype="multipart/form-data" action="{{ $imagem->exists?route('biblioteca_imagens.update',$imagem):route('biblioteca_imagens.store') }}">@csrf @if($imagem->exists)@method('PUT')@endif
<div class="card content-card"><div class="card-body p-4">
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif<div id="editorAlert" class="alert alert-danger d-none"></div>
<div class="row g-3"><div class="col-md-5"><label class="form-label">Nome *</label><input name="nome" maxlength="120" required class="form-control" value="{{ old('nome',$imagem->nome) }}"></div><div class="col-md-4"><label class="form-label">Categoria *</label><select name="categoria" class="form-select" required>@foreach($categories as $key=>$label)<option value="{{ $key }}" @selected(old('categoria',$imagem->categoria)===$key)>{{ $label }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Status *</label><select name="ativo" class="form-select"><option value="1" @selected(old('ativo',$imagem->exists?(int)$imagem->ativo:1)==1)>Ativa</option><option value="0" @selected(old('ativo',$imagem->exists?(int)$imagem->ativo:1)==0)>Inativa</option></select></div>
<div class="col-12"><label class="form-label">Imagem {{ $imagem->exists?'':'*' }}</label><input id="imageInput" type="file" name="imagem" class="d-none" accept="image/png,image/jpeg,image/webp" @required(!$imagem->exists)>
<div id="dropArea" class="image-drop {{ $imagem->url()?'d-none':'' }}" tabindex="0"><i class="bi bi-cloud-arrow-up fs-2 text-primary"></i><div class="fw-semibold mt-2">Clique para selecionar ou cole uma imagem aqui</div><div class="text-muted small">PNG, JPG ou WebP, com até 10 MB</div></div>
<div id="editorArea" class="{{ $imagem->url()?'':'d-none' }}"><div class="image-editor rounded border overflow-hidden"><img id="editorImage" @if($imagem->url()) src="{{ $imagem->url() }}" @endif alt="Editor da imagem"></div><div class="d-flex flex-wrap align-items-end gap-2 mt-3"><button id="applyCrop" type="button" class="btn btn-outline-primary"><i class="bi bi-crop me-1"></i>Aplicar recorte</button><button id="removeBackground" type="button" class="btn btn-outline-secondary"><i class="bi bi-magic me-1"></i>Remover fundo</button><div><label for="tolerance" class="form-label small mb-0">Tolerância: <span id="toleranceValue">45</span></label><input id="tolerance" type="range" class="form-range" min="10" max="120" value="45" style="width:180px"></div><button id="replaceImage" type="button" class="btn btn-outline-secondary"><i class="bi bi-arrow-repeat me-1"></i>Trocar imagem</button></div><div class="form-text">A remoção usa a média das cores dos quatro cantos. Ajuste a tolerância para melhorar o resultado.</div><div id="processedArea" class="d-none mt-3"><div class="form-label fw-semibold">Resultado que será salvo</div><div class="border rounded bg-white p-2"><img id="processedImage" class="image-result" alt="Resultado processado"></div></div></div></div></div>
<fieldset class="border rounded p-3 mt-4"><legend class="float-none w-auto px-2 h5 mb-0">Vetorização</legend><textarea id="svgCode" name="svg" class="d-none">{{ old('svg',$imagem->svg) }}</textarea><div class="d-flex flex-wrap align-items-end gap-3 mb-3"><div><label for="vectorColors" class="form-label small mb-1">Quantidade máxima de cores</label><select id="vectorColors" class="form-select form-select-sm"><option>2</option><option>4</option><option selected>8</option><option>12</option><option>16</option></select></div><button id="vectorizeImage" type="button" class="btn btn-outline-primary"><i class="bi bi-bezier2 me-1"></i>Vetorizar imagem sem fundo</button><button id="removeVector" type="button" class="btn btn-outline-danger"><i class="bi bi-trash me-1"></i>Remover vetorização</button></div><div id="vectorAlert" class="alert alert-danger d-none"></div><div class="row g-3"><div class="col-lg-9"><div id="vectorPreview" class="vector-preview border rounded" title="Clique para selecionar uma cor. Use o botão direito para zoom e Ctrl + arrastar para mover."></div></div><div class="col-lg-3"><div id="vectorColorPanel" class="vector-color-panel border rounded p-3 bg-light"><p class="small text-muted mb-0">Clique em uma parte do SVG para editar sua cor.</p></div><div class="alert alert-info small mt-3 mb-0"><div><strong>Zoom:</strong> botão direito + arrastar para cima ou para baixo.</div><div class="mt-1"><strong>Mover:</strong> Ctrl + arrastar com o botão esquerdo.</div><div class="mt-1"><strong>Cor:</strong> clique em uma área da imagem.</div></div></div></div></fieldset>
<div class="d-flex justify-content-end gap-2 mt-4"><a href="{{ route('biblioteca_imagens.index') }}" class="btn btn-outline-secondary"><i class="bi bi-arrow-left me-1"></i>Voltar</a><button class="btn btn-primary"><i class="bi bi-check-lg me-1"></i>Salvar</button></div></div></div></form>
@endsection
@push('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.6.2/cropper.min.js"></script>
<script>
document.addEventListener('DOMContentLoaded',()=>{
 const input=document.getElementById('imageInput'),drop=document.getElementById('dropArea'),area=document.getElementById('editorArea'),image=document.getElementById('editorImage'),resultArea=document.getElementById('processedArea'),result=document.getElementById('processedImage'),alertBox=document.getElementById('editorAlert'),tolerance=document.getElementById('tolerance'),toleranceValue=document.getElementById('toleranceValue');let cropper=null,sourceUrl=null,resultUrl=null;
 const error=m=>{alertBox.textContent=m;alertBox.classList.remove('d-none')},clear=()=>alertBox.classList.add('d-none'),revoke=()=>{if(sourceUrl)URL.revokeObjectURL(sourceUrl);if(resultUrl)URL.revokeObjectURL(resultUrl);sourceUrl=resultUrl=null};
 const init=()=>{if(cropper)cropper.destroy();cropper=new Cropper(image,{viewMode:1,autoCropArea:1,background:false,responsive:true});area.classList.remove('d-none');drop.classList.add('d-none')};if(image.src){if(image.complete)init();else image.addEventListener('load',init,{once:true})}
 const load=file=>{clear();if(!['image/png','image/jpeg','image/webp'].includes(file.type)){error('Selecione uma imagem PNG, JPG ou WebP.');return}if(file.size>10*1024*1024){error('A imagem deve ter no máximo 10 MB.');return}revoke();sourceUrl=URL.createObjectURL(file);image.onload=init;image.src=sourceUrl;resultArea.classList.add('d-none');const transfer=new DataTransfer();transfer.items.add(file);input.files=transfer.files};
 const exportImage=removeBg=>{if(!cropper)return;clear();const canvas=cropper.getCroppedCanvas({imageSmoothingEnabled:true,imageSmoothingQuality:'high'});if(removeBg){const ctx=canvas.getContext('2d'),pixels=ctx.getImageData(0,0,canvas.width,canvas.height),data=pixels.data,corners=[[0,0],[canvas.width-1,0],[0,canvas.height-1],[canvas.width-1,canvas.height-1]],bg=[0,0,0];corners.forEach(([x,y])=>{const i=(y*canvas.width+x)*4;bg[0]+=data[i]/4;bg[1]+=data[i+1]/4;bg[2]+=data[i+2]/4});const limit=Number(tolerance.value);for(let i=0;i<data.length;i+=4){const distance=Math.sqrt((data[i]-bg[0])**2+(data[i+1]-bg[1])**2+(data[i+2]-bg[2])**2);if(distance<=limit)data[i+3]=0;else if(distance<limit+25)data[i+3]=Math.round(data[i+3]*(distance-limit)/25)}ctx.putImageData(pixels,0,0)}canvas.toBlob(blob=>{if(!blob){error('Não foi possível processar a imagem.');return}if(blob.size>10*1024*1024){error('O resultado ultrapassa 10 MB.');return}if(resultUrl)URL.revokeObjectURL(resultUrl);resultUrl=URL.createObjectURL(blob);result.src=resultUrl;resultArea.classList.remove('d-none');const file=new File([blob],'imagem-processada.png',{type:'image/png'}),transfer=new DataTransfer();transfer.items.add(file);input.files=transfer.files;document.dispatchEvent(new CustomEvent('library-image-processed'))},'image/png')};
 window.getLibraryVectorSourceCanvas=async()=>{if(!resultArea.classList.contains('d-none')&&result.src){const source=new Image();await new Promise((resolve,reject)=>{source.onload=resolve;source.onerror=reject;source.src=result.src});const canvas=document.createElement('canvas');canvas.width=source.naturalWidth;canvas.height=source.naturalHeight;canvas.getContext('2d').drawImage(source,0,0);return canvas}return cropper?.getCroppedCanvas({imageSmoothingEnabled:true,imageSmoothingQuality:'high'})||null};
 drop.addEventListener('click',()=>input.click());drop.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();input.click()}});document.getElementById('replaceImage').addEventListener('click',()=>input.click());input.addEventListener('change',()=>input.files[0]&&load(input.files[0]));document.addEventListener('paste',e=>{const file=[...e.clipboardData.items].find(i=>i.type.startsWith('image/'))?.getAsFile();if(file){e.preventDefault();load(file)}});document.getElementById('applyCrop').addEventListener('click',()=>exportImage(false));document.getElementById('removeBackground').addEventListener('click',()=>exportImage(true));tolerance.addEventListener('input',()=>toleranceValue.textContent=tolerance.value);
});
</script>
<script src="{{ asset('biblioteca-image-vectorizer.js') }}?v={{ filemtime(public_path('biblioteca-image-vectorizer.js')) }}"></script>
@endpush
