@extends('layouts.app')
@section('title','Participantes da emissão')
@push('styles')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css" rel="stylesheet">
@endpush
@section('content')
<div class="d-flex justify-content-between"><h1 class="page-title">Participantes da emissão #{{ $certificado->id }}</h1>@if(in_array('emissoes.gerar_pdfs',$permissions,true)&&$items->isNotEmpty())<div class="btn-group"><button id="bulkGenerateButton" type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-hourglass-split me-1"></i>Gerar certificados pendentes</button><ul class="dropdown-menu dropdown-menu-end"><li><button type="button" class="dropdown-item js-generate-pending" data-kind="pdf"><i class="bi bi-file-earmark-pdf me-2 text-danger"></i>PDF</button></li><li><button type="button" class="dropdown-item js-generate-pending" data-kind="img"><i class="bi bi-image me-2 text-primary"></i>Imagem</button></li></ul></div>@endif</div>
@if(session('status'))<div class="alert alert-success mt-3">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert alert-danger mt-3">{{ $errors->first() }}</div>@endif
@if(in_array('emissoes.inserir_participantes',$permissions,true) || in_array('emissoes.inserir_participantes_proprios',$permissions,true))
@php($spreadsheetMode=$importAnalysis!==null||session('participant_add_mode')==='spreadsheet')
<div class="card content-card my-4"><div class="card-body"><label for="participantAddMode" class="form-label fw-semibold">Como adicionar participantes?</label><select id="participantAddMode" class="form-select" style="max-width:360px"><option value="list" @selected(!$spreadsheetMode)>Selecionar na lista</option><option value="spreadsheet" @selected($spreadsheetMode)>Adicionar planilha</option></select></div></div>
<form id="participantListCard" method="POST" action="{{ route('emissoes.participantes.store',$certificado) }}" class="card content-card mb-4 {{ $spreadsheetMode?'d-none':'' }}"><div class="card-body">@csrf<label class="form-label">Adicionar participantes</label><select id="participantes" name="participantes[]" class="form-select" multiple required></select>@if($templateFields)<div class="row g-3 mt-1">@foreach($templateFields as $field)<div class="col-md-6"><label class="form-label">{{ $field['nome'] }} *</label>@if($field['tipo']==='lista')<select name="campos[{{ $field['nome'] }}]" class="form-select" required><option value="">Selecione</option>@foreach($field['opcoes']??[] as $option)<option value="{{ $option }}">{{ $option }}</option>@endforeach</select>@elseif($field['tipo']==='textarea')<textarea name="campos[{{ $field['nome'] }}]" class="form-control" required></textarea>@else<input name="campos[{{ $field['nome'] }}]" type="{{ $field['tipo']==='data'?'date':($field['tipo']==='number'?'number':'text') }}" class="form-control" required>@endif</div>@endforeach</div>@endif<div class="text-end mt-3"><button class="btn btn-primary">Adicionar selecionados</button></div></div></form>
<div id="participantSpreadsheetCard" class="{{ $spreadsheetMode?'':'d-none' }}">
<form method="POST" enctype="multipart/form-data" action="{{ route('emissoes.participantes.spreadsheet.analyze',$certificado) }}" class="card content-card mb-4"><div class="card-body">@csrf<div class="d-flex justify-content-between align-items-center mb-2"><label for="participantSpreadsheet" class="form-label fw-semibold mb-0">Planilha de participantes</label><a href="{{ route('emissoes.participantes.spreadsheet.example',$certificado) }}" class="btn btn-sm btn-outline-success"><i class="bi bi-file-earmark-excel me-1"></i>Baixar planilha de exemplo</a></div><div class="input-group"><input id="participantSpreadsheet" name="planilha" type="file" class="form-control" accept=".csv,.xls,.xlsx,.ods,.odt" required><button class="btn btn-outline-primary"><i class="bi bi-upload me-1"></i>Analisar planilha</button></div><div class="form-text">Formatos: CSV, XLS, XLSX, ODS ou ODT, até 10 MB. São obrigatórias as colunas <strong>nome</strong>, <strong>email</strong>@if($templateFields) e <strong>{{ collect($templateFields)->pluck('nome')->implode(', ') }}</strong>@endif.</div></div></form>
@if($importAnalysis)
<form id="spreadsheetImportForm" method="POST" action="{{ route('emissoes.participantes.spreadsheet.import',$certificado) }}" class="card content-card mb-4">@csrf<div class="card-header"><h2 class="h5 mb-0">Relatório da planilha</h2></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Linha</th><th>ID</th><th>Nome</th><th>E-mail</th><th>Status</th><th>Ação</th></tr></thead><tbody>
@foreach($importAnalysis['rows'] as $row)
<tr class="import-row" data-kind="{{ $row['kind'] }}"><td>{{ $row['line'] }}</td><td>@if($row['existing_id'])<span class="badge text-bg-secondary">{{ $row['existing_id'] }}</span>@elseif($row['kind']==='new')<span class="badge text-bg-success">Novo</span>@else—@endif</td>
<td>@if($row['nome']==='')<input name="rows[{{ $row['index'] }}][nome]" class="form-control form-control-sm import-name" placeholder="Informe o nome" value="{{ old('rows.'.$row['index'].'.nome') }}">@else{{ $row['nome'] }}@endif</td>
<td>@if($row['email']===''||($row['kind']==='incomplete'&&!filter_var($row['email'],FILTER_VALIDATE_EMAIL)))<input name="rows[{{ $row['index'] }}][email]" type="email" class="form-control form-control-sm import-email" placeholder="Informe o e-mail" value="{{ old('rows.'.$row['index'].'.email',$row['email']) }}">@else{{ $row['email'] }}@endif</td>
<td><span class="badge {{ in_array($row['kind'],['new','recovered'],true)?'text-bg-success':($row['kind']==='conflict'?'text-bg-warning':'text-bg-secondary') }}">{{ $row['status'] }}</span>@if($row['existing_label'])<div class="small text-muted mt-1">{{ $row['existing_label'] }}</div>@endif</td>
<td>@if($row['kind']==='conflict')<select name="rows[{{ $row['index'] }}][action]" class="form-select form-select-sm import-action" required><option value="">Selecione</option><option value="use_existing" @selected(old('rows.'.$row['index'].'.action')==='use_existing')>Usar o participante da lista</option><option value="create_new" @selected(old('rows.'.$row['index'].'.action')==='create_new')>Criar um novo participante</option></select>@elseif($row['kind']==='incomplete')<select name="rows[{{ $row['index'] }}][action]" class="form-select form-select-sm import-action"><option value="">Preencher informação</option><option value="skip" @selected(old('rows.'.$row['index'].'.action')==='skip')>Não importar</option></select>@else<span class="text-muted small">Automática</span>@endif</td></tr>
@endforeach
</tbody></table></div></div><div class="card-footer"><div class="row g-2 mb-3"><div class="col-6 col-md"><div class="border rounded p-2"><strong>{{ $importAnalysis['summary']['total'] }}</strong><div class="small text-muted">na planilha</div></div></div><div class="col-6 col-md"><div class="border rounded p-2"><strong>{{ $importAnalysis['summary']['ready'] }}</strong><div class="small text-muted">prontos</div></div></div><div class="col-6 col-md"><div class="border rounded p-2"><strong>{{ $importAnalysis['summary']['new'] }}</strong><div class="small text-muted">novos</div></div></div><div class="col-6 col-md"><div class="border rounded p-2"><strong>{{ $importAnalysis['summary']['recovered'] }}</strong><div class="small text-muted">da lista</div></div></div><div class="col-6 col-md"><div class="border rounded p-2"><strong>{{ $importAnalysis['summary']['linked']+$importAnalysis['summary']['repeated'] }}</strong><div class="small text-muted">repetidos</div></div></div><div class="col-6 col-md"><div class="border rounded p-2"><strong>{{ $importAnalysis['summary']['incomplete'] }}</strong><div class="small text-muted">incompletos</div></div></div></div><div id="importResolutionMessage" class="small text-danger mb-2"></div><div class="text-end"><button id="importSpreadsheetButton" class="btn btn-success" disabled><i class="bi bi-people-fill me-1"></i>Importar participantes</button></div></div></form>
@endif
</div>
@endif
<div class="card content-card"><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>ID</th><th>Nome</th><th>E-mail</th>@foreach($templateFields as $field)<th>{{ $field['nome'] }}</th>@endforeach<th>PDF</th><th>IMG</th><th>Ações</th></tr></thead><tbody>
@forelse($items as $item)
<tr><td>{{ $item->participante_id }}</td><td>{{ $item->participante?->nome??'—' }}</td><td>{{ $item->participante?->email??'—' }}</td>@foreach($templateFields as $field)<td>{{ data_get($item->dados_personalizados,$field['nome'],'—') }}</td>@endforeach
<td>@if($item->arquivoExists() && in_array('emissoes.visualizar',$permissions,true))<a target="_blank" rel="noopener noreferrer" href="{{ route('emissoes.participantes.pdf',[$certificado,$item]) }}" class="btn btn-sm btn-outline-danger listagem-acao" title="Abrir PDF" aria-label="Abrir PDF"><i class="bi bi-file-earmark-pdf-fill"></i></a>@elseif(in_array('emissoes.gerar_pdfs',$permissions,true))<form method="POST" action="{{ route('emissoes.participantes.generate',[$certificado,$item]) }}" class="d-inline js-generate-certificate" data-kind="pdf">@csrf<button class="btn btn-sm btn-link p-0">Gerar PDF</button></form>@elseif($item->erro_geracao)<span class="text-danger" title="{{ $item->erro_geracao }}">Erro</span>@else<span class="text-muted">Pendente</span>@endif</td>
<td>@if($item->imagemExists() && filled($item->codigo_img) && in_array('emissoes.visualizar',$permissions,true))<a target="_blank" rel="noopener noreferrer" href="{{ route('certificadosnovos.public.image',$item->codigo_img) }}" class="btn btn-sm btn-outline-primary listagem-acao" title="Abrir imagem" aria-label="Abrir imagem"><i class="bi bi-image-fill"></i></a>@elseif(in_array('emissoes.gerar_pdfs',$permissions,true))<form method="POST" action="{{ route('emissoes.participantes.generate-image',[$certificado,$item]) }}" class="d-inline js-generate-certificate" data-kind="img">@csrf<button class="btn btn-sm btn-link p-0">Gerar IMG</button></form>@else<span class="text-muted">Pendente</span>@endif</td>
<td>@if(in_array('emissoes.excluir_participantes',$permissions,true))<form method="POST" action="{{ route('emissoes.participantes.destroy',[$certificado,$item]) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form>@endif</td></tr>
@empty
<tr><td colspan="{{ 6+count($templateFields) }}" class="text-center text-muted">Nenhum participante adicionado.</td></tr>
@endforelse
</tbody></table></div></div></div><div class="text-end mt-3"><a href="{{ route('emissoes.show',$certificado) }}" class="btn btn-outline-secondary">Voltar</a></div>
@endsection
@push('scripts')
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
$('#participantes').select2({theme:'bootstrap-5',width:'100%',placeholder:'Pesquise por nome ou e-mail',ajax:{url:@json(route('emissoes.participantes.opcoes',$certificado,false)),dataType:'json',data:p=>({q:p.term||'',page:p.page||1}),processResults:r=>r}});
const addMode=document.getElementById('participantAddMode'),listCard=document.getElementById('participantListCard'),spreadsheetCard=document.getElementById('participantSpreadsheetCard');
addMode?.addEventListener('change',()=>{const spreadsheet=addMode.value==='spreadsheet';listCard?.classList.toggle('d-none',spreadsheet);spreadsheetCard?.classList.toggle('d-none',!spreadsheet)});
const importButton=document.getElementById('importSpreadsheetButton'),resolutionMessage=document.getElementById('importResolutionMessage');
const validateImportRows=()=>{if(!importButton)return;let unresolved=0;document.querySelectorAll('.import-row').forEach(row=>{const kind=row.dataset.kind,action=row.querySelector('.import-action')?.value||'',name=row.querySelector('.import-name'),email=row.querySelector('.import-email');if(kind==='conflict'&&!action)unresolved++;if(kind==='incomplete'&&action!=='skip'&&((name&&!name.value.trim())||(email&&(!email.value.trim()||!email.checkValidity()))))unresolved++});importButton.disabled=unresolved>0;resolutionMessage.textContent=unresolved?`Resolva ${unresolved} linha(s) antes de importar.`:''};
document.getElementById('spreadsheetImportForm')?.addEventListener('input',validateImportRows);document.getElementById('spreadsheetImportForm')?.addEventListener('change',validateImportRows);validateImportRows();
const pendingForms=kind=>[...document.querySelectorAll(`.js-generate-certificate[data-kind="${kind}"]`)];
const refreshBulkOptions=()=>{document.querySelectorAll('.js-generate-pending').forEach(option=>{if(!option.dataset.processing)option.disabled=pendingForms(option.dataset.kind).length===0});const main=document.getElementById('bulkGenerateButton');if(main)main.disabled=[...document.querySelectorAll('.js-generate-pending')].every(option=>option.disabled)};
const generateForm=async form=>{const cell=form.closest('td'),original=cell.innerHTML,action=form.action,token=form.querySelector('[name="_token"]').value;cell.innerHTML='<span class="spinner-border spinner-border-sm text-primary" role="status"><span class="visually-hidden">Gerando...</span></span>';try{const response=await fetch(action,{method:'POST',headers:{'X-CSRF-TOKEN':token,'Accept':'application/json'}}),data=await response.json();if(!response.ok)throw new Error(data.message||'Não foi possível gerar.');cell.innerHTML=data.html;return data}catch(error){cell.innerHTML=original;throw error}finally{refreshBulkOptions()}};
document.addEventListener('submit',async event=>{const form=event.target.closest('.js-generate-certificate');if(!form)return;event.preventDefault();try{await generateForm(form)}catch(error){alert(error.message)}});
document.addEventListener('click',async event=>{const option=event.target.closest('.js-generate-pending');if(!option||option.disabled)return;const forms=pendingForms(option.dataset.kind);if(!forms.length)return;const original=option.innerHTML;option.dataset.processing='1';option.disabled=true;option.innerHTML='<span class="spinner-border spinner-border-sm me-2" role="status"></span>Processando '+(option.dataset.kind==='pdf'?'PDF':'Imagem');const results=await Promise.allSettled(forms.map(generateForm));delete option.dataset.processing;option.innerHTML=original;refreshBulkOptions();const failures=results.filter(result=>result.status==='rejected');if(failures.length)alert(`${failures.length} certificado(s) não puderam ser gerados.`)});
refreshBulkOptions();
</script>
@endpush
