@extends('layouts.app')
@section('title',$assinatura->exists?'Editar assinatura':'Nova assinatura')
@push('styles')<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css" rel="stylesheet">@endpush
@section('content')
<div class="mb-4"><h1 class="page-title">{{ $assinatura->exists?'Editar assinatura':'Nova assinatura' }}</h1></div><form method="POST" action="{{ $assinatura->exists?route('assinaturas_template.update',$assinatura):route('assinaturas_template.store') }}">@csrf @if($assinatura->exists)@method('PUT')@endif<div class="card content-card"><div class="card-body p-4">@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif<div class="row g-3">
<div class="col-12 col-md-6"><label class="form-label">Participante</label><select id="participante_id" name="participante_id" class="form-select"><option></option>@if(old('participante_id',$assinatura->participante_id))<option value="{{ old('participante_id',$assinatura->participante_id) }}" selected>{{ $assinatura->participante?->nome??'Participante selecionado' }}</option>@endif</select></div>
<div class="col-12 col-md-6"><label class="form-label">Template</label><select id="template_id" name="template_id" class="form-select"><option></option>@if(old('template_id',$assinatura->template_id))<option value="{{ old('template_id',$assinatura->template_id) }}" selected>#{{ $assinatura->template?->id }} - {{ $assinatura->template?->nome }} - ({{ $assinatura->template?->pagina }} - {{ $assinatura->template?->layout_pagina }})</option>@endif</select></div>
<div class="col-12 col-md-5"><label class="form-label">Titulação</label><input name="titulacao" maxlength="20" class="form-control" value="{{ old('titulacao',$assinatura->titulacao) }}"></div><div class="col-6 col-md-4"><label class="form-label">Rubrica ID</label><input name="rubrica_id" type="number" min="1" class="form-control" value="{{ old('rubrica_id',$assinatura->rubrica_id) }}"></div><div class="col-6 col-md-3"><label class="form-label">Status *</label><select name="ativo" class="form-select" required><option value="1" @selected((string)old('ativo',$assinatura->exists?(int)$assinatura->ativo:1)==='1')>Ativa</option><option value="0" @selected((string)old('ativo',$assinatura->exists?(int)$assinatura->ativo:1)==='0')>Inativa</option></select></div>
</div><div class="d-flex justify-content-end gap-2 mt-4"><a href="{{ route('assinaturas_template.index') }}" class="btn btn-outline-secondary">Cancelar</a><button class="btn btn-primary">Salvar</button></div></div></div></form>
@endsection
@push('scripts')<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script><script>document.addEventListener('DOMContentLoaded',()=>{const setup=(id,url,text)=>$(id).select2({theme:'bootstrap-5',width:'100%',placeholder:text,allowClear:true,ajax:{url,dataType:'json',delay:250,data:p=>({q:p.term||'',page:p.page||1}),processResults:r=>r}});setup('#participante_id',@json(route('assinaturas_template.participantes',[],false)),'Pesquise o participante');setup('#template_id',@json(route('assinaturas_template.templates',[],false)),'Pesquise o template')});</script>@endpush
