@extends('layouts.app')
@section('title',$certificado->exists?'Editar certificado':'Novo certificado')
@push('styles')<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css" rel="stylesheet">@endpush
@section('content')
<div class="mb-4"><h1 class="page-title">{{ $certificado->exists?'Editar certificado':'Novo certificado' }}</h1><p class="page-description mb-0">Preencha os dados do certificado.</p></div>
<form method="POST" action="{{ $certificado->exists?route('certificados.update',$certificado):route('certificados.store') }}">@csrf @if($certificado->exists)@method('PUT')@endif
<div class="card content-card"><div class="card-header"><h2 class="h5 fw-bold mb-0">Dados do certificado</h2></div><div class="card-body p-4">@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif<div class="row g-3">
<div class="col-12 col-md-6"><label for="participanteId" class="form-label">Participante</label><select id="participanteId" name="participanteId" class="form-select"><option value=""></option>@if(old('participanteId',$certificado->participanteId))<option value="{{ old('participanteId',$certificado->participanteId) }}" selected>{{ $certificado->participante?->nome ?? 'Participante selecionado' }}</option>@endif</select></div>
<div class="col-12 col-md-6"><label for="atividadeId" class="form-label">Atividade</label><select id="atividadeId" name="atividadeId" class="form-select"><option value=""></option>@if(old('atividadeId',$certificado->atividadeId))<option value="{{ old('atividadeId',$certificado->atividadeId) }}" selected>{{ $certificado->atividade?->nome ?? 'Atividade selecionada' }}</option>@endif</select></div>
<div class="col-12"><label for="nome" class="form-label">Nome</label><input id="nome" name="nome" class="form-control" maxlength="600" value="{{ old('nome',$certificado->nome) }}"></div>
@foreach([['titulo','Título',256],['titulo2','Título 2',256],['titulo3','Título 3',256],['titulo4','Título 4',100]] as [$field,$label,$max])<div class="col-12 col-md-6"><label for="{{ $field }}" class="form-label">{{ $label }}</label><input id="{{ $field }}" name="{{ $field }}" class="form-control" maxlength="{{ $max }}" value="{{ old($field,$certificado->{$field}) }}"></div>@endforeach
<div class="col-12 col-md-3"><label for="cargaHoraria" class="form-label">Carga horária</label><input id="cargaHoraria" type="number" min="0" name="cargaHoraria" class="form-control" value="{{ old('cargaHoraria',$certificado->cargaHoraria) }}"></div>
<div class="col-12 col-md-3"><label for="tipo" class="form-label">Tipo</label><input id="tipo" name="tipo" class="form-control" maxlength="50" value="{{ old('tipo',$certificado->tipo) }}"></div>
<div class="col-12 col-md-3"><label for="arquivo" class="form-label">Arquivo</label><input id="arquivo" name="arquivo" class="form-control" maxlength="50" value="{{ old('arquivo',$certificado->arquivo) }}"></div>
<div class="col-12 col-md-3"><label for="arquivo_old" class="form-label">Arquivo anterior</label><input id="arquivo_old" name="arquivo_old" class="form-control" maxlength="50" value="{{ old('arquivo_old',$certificado->arquivo_old) }}"></div>
<div class="col-12 col-md-3"><label for="ativo" class="form-label">Status *</label><select id="ativo" name="ativo" class="form-select" required><option value="1" @selected((string)old('ativo',$certificado->exists?(int)$certificado->ativo:1)==='1')>Ativo</option><option value="0" @selected((string)old('ativo',$certificado->exists?(int)$certificado->ativo:1)==='0')>Inativo</option></select></div>
<div class="col-12"><label for="outrosParticipantes" class="form-label">Outros participantes</label><textarea id="outrosParticipantes" name="outrosParticipantes" class="form-control" maxlength="700" rows="3">{{ old('outrosParticipantes',$certificado->outrosParticipantes) }}</textarea></div>
</div><div class="d-flex justify-content-end gap-2 mt-4"><a href="{{ route('certificados.index') }}" class="btn btn-outline-secondary">Cancelar</a><button class="btn btn-primary"><i class="bi bi-check-lg me-1"></i>Salvar</button></div></div></div></form>
@endsection
@push('scripts')<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script><script>document.addEventListener('DOMContentLoaded',()=>{const setup=(selector,url,placeholder)=>$(selector).select2({theme:'bootstrap-5',width:'100%',placeholder,allowClear:true,ajax:{url,dataType:'json',delay:250,data:p=>({q:p.term||'',page:p.page||1}),processResults:r=>r}});setup('#participanteId',@json(route('certificados.participantes',[],false)),'Pesquise um participante');setup('#atividadeId',@json(route('certificados.atividades',[],false)),'Pesquise uma atividade')});</script>@endpush
