@extends('layouts.app')
@section('title','Construtor de layouts')
@push('styles')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css" rel="stylesheet">
<style>
.builder-page{height:calc(100vh - 50px);min-height:650px;display:flex;flex-direction:column}.builder-header{flex:0 0 auto}.builder-workspace{display:grid;grid-template-columns:minmax(230px,20%) minmax(0,80%);gap:1rem;min-height:0;flex:1}.builder-sidebar{min-height:0;overflow-y:auto}.builder-canvas-area{min-width:0;min-height:0;overflow:auto;background:#e8ebf0;border-radius:14px;padding:1.25rem;display:flex;align-items:flex-start;justify-content:center}.layout-canvas{position:relative;width:min(100%,calc((100vh - 190px) * var(--ratio)));aspect-ratio:var(--ratio);flex:0 0 auto;background:#fff center/100% 100% no-repeat;box-shadow:0 8px 25px #24304726;overflow:hidden;user-select:none}.layout-element{position:absolute;min-width:8px;min-height:8px;border:1px dashed transparent;cursor:move;overflow:hidden}.layout-element.selected{border-color:#0d6efd;box-shadow:0 0 0 2px #0d6efd26}.layout-element img{width:100%;height:100%;display:block;object-fit:contain;pointer-events:none}.layout-element-text{white-space:pre-wrap;line-height:1.15;font-size:clamp(8px,1.25vw,18px);padding:2px}.resize-handle{display:none;position:absolute;right:-1px;bottom:-1px;width:12px;height:12px;background:#0d6efd;border:2px solid #fff;cursor:nwse-resize}.layout-element.selected .resize-handle{display:block}.variable-button{text-align:left;width:100%;border:1px solid #dee2e6;background:#fff;border-radius:.6rem;padding:.65rem;display:flex;align-items:center;gap:.6rem}.variable-button:hover{border-color:#0d6efd;background:#f6f9ff}.variable-thumb{width:34px;height:34px;object-fit:contain;border-radius:.3rem}.empty-background{position:absolute;inset:0;display:grid;place-items:center;color:#8490a4;pointer-events:none}.properties-panel{border-top:1px solid #e5e7eb;margin-top:1rem;padding-top:1rem}.sidebar-sticky-title{position:sticky;top:0;background:#fff;z-index:2;padding-bottom:.5rem}@media(max-width:767.98px){.builder-page{height:auto}.builder-workspace{grid-template-columns:1fr}.builder-sidebar{max-height:42vh}.builder-canvas-area{min-height:60vh}.layout-canvas{width:100%}}
</style>
@endpush
@section('content')
<div class="builder-page">
    <div class="builder-header mb-3 d-flex justify-content-between align-items-start gap-3">
        <div><h1 class="page-title">{{ $template->nome ?: 'Template sem nome' }}</h1><p class="page-description mb-0">{{ $template->pagina ?: 'Página personalizada' }} · {{ $template->layout_pagina ?: 'Sem orientação' }} · {{ $template->largura }} × {{ $template->altura }} mm</p></div>
        <div class="d-flex gap-2"><button id="testTemplate" type="button" class="btn btn-outline-success" title="Testar com dados reais"><i class="bi bi-person-check me-1"></i>Testar template</button><button id="previewPdf" type="button" class="btn btn-outline-danger" title="Abrir preview em PDF"><i class="bi bi-file-earmark-pdf me-1"></i>Preview PDF</button><a href="{{ route('templates.index') }}" class="btn btn-outline-secondary">Voltar</a><button form="builderForm" class="btn btn-primary"><i class="bi bi-check-lg me-1"></i>Salvar</button></div>
    </div>
    @if(session('status'))<div class="alert alert-success py-2">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger py-2">Não foi possível salvar o layout. Revise os elementos.</div>@endif
    <form id="builderForm" method="POST" action="{{ route('templates.builder.save',$template) }}" class="builder-workspace">@csrf @method('PUT')<input type="hidden" id="layoutJson" name="layout_json">
        <aside class="card content-card builder-sidebar"><div class="card-body p-3">
            <div class="sidebar-sticky-title"><div class="d-flex justify-content-between align-items-center"><h2 class="h6 fw-bold mb-1">Elementos</h2><button type="button" id="importFont" class="btn btn-sm btn-outline-primary" title="Importar arquivo de fonte"><i class="bi bi-upload me-1"></i>Fonte</button></div><p class="small text-muted mb-0">Adicione conteúdo diretamente ao template.</p><input id="fontFile" type="file" class="d-none" accept=".ttf,.otf,.woff,.woff2,font/ttf,font/otf,font/woff,font/woff2"><div id="fontMessage" class="small mt-1 d-none"></div></div>
            <div class="d-grid gap-2 mt-2"><button id="addText" type="button" class="variable-button"><span class="context-icon"><i class="bi bi-fonts"></i></span><span><strong class="d-block small">Texto simples</strong><span class="small text-muted">Fixo ou campo dinâmico</span></span></button><button id="addRichText" type="button" class="variable-button"><span class="context-icon"><i class="bi bi-text-paragraph"></i></span><span><strong class="d-block small">Texto formatado</strong><span class="small text-muted">Frase, estilos e variáveis</span></span></button><button id="addImage" type="button" class="variable-button"><span class="context-icon"><i class="bi bi-image"></i></span><span><strong class="d-block small">Imagem</strong><span class="small text-muted">Biblioteca ou rubrica</span></span></button></div>
            <div id="properties" class="properties-panel d-none"><div class="d-flex justify-content-between align-items-center mb-2"><h2 class="h6 fw-bold mb-0">Elemento selecionado</h2><div class="d-flex gap-1"><button type="button" id="rotateElement" class="btn btn-sm btn-outline-secondary d-none" title="Girar imagem 90° no sentido horário" aria-label="Girar imagem 90 graus no sentido horário"><i class="bi bi-arrow-clockwise"></i></button><button type="button" id="duplicateElement" class="btn btn-sm btn-outline-primary" title="Duplicar elemento" aria-label="Duplicar elemento"><i class="bi bi-copy"></i></button><button type="button" id="removeElement" class="btn btn-sm btn-outline-danger" title="Remover elemento" aria-label="Remover elemento"><i class="bi bi-trash"></i></button></div></div>
                <div class="mb-2"><label class="form-label small">Origem</label><select id="propSourceType" class="form-select form-select-sm"><option value="fixed">Conteúdo fixo</option><option value="dynamic">Campo dinâmico</option><option value="library">Biblioteca de imagens</option><option value="responsible_signature">Rubrica do responsável</option></select></div>
                <div id="dynamicProperty" class="mb-2 d-none"><label class="form-label small">Campo dinâmico</label><select id="propSourceKey" class="form-select form-select-sm">@foreach($dynamicSources as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div>
                <div id="libraryProperty" class="mb-2 d-none"><label class="form-label small">Imagem da biblioteca</label><select id="propLibraryImage" class="form-select form-select-sm"><option value="">Selecione</option>@foreach($libraryImages as $image)<option value="{{ $image->id }}" data-url="{{ $image->url() }}">{{ $image->nome }} · {{ ucfirst($image->categoria) }}</option>@endforeach</select><a href="{{ route('biblioteca_imagens.create') }}" class="small" target="_blank">Adicionar imagem à biblioteca</a></div>
                <div id="responsibleSignatureProperty" class="mb-2 d-none"><label class="form-label small">Rubrica do responsável</label><select id="propResponsibleSignature" class="form-select form-select-sm"><option value="">Automática · responsável da emissão</option>@foreach($responsibleSignatures as $signature)<option value="{{ $signature->id }}" data-url="{{ $signature->signatureUrl() }}">{{ $signature->participante?->nome }} · Rubrica #{{ $signature->id }}</option>@endforeach</select><div class="form-text">Sem uma escolha específica, será usada a rubrica do responsável definido na emissão.</div></div>
                <div id="textProperty" class="mb-2"><label class="form-label small">Conteúdo</label><div id="richToolbar" class="btn-group btn-group-sm mb-1 d-none"><button type="button" class="btn btn-outline-secondary" data-tag="strong" title="Negrito"><i class="bi bi-type-bold"></i></button><button type="button" class="btn btn-outline-secondary" data-tag="em" title="Itálico"><i class="bi bi-type-italic"></i></button><button type="button" class="btn btn-outline-secondary" data-tag="u" title="Sublinhado"><i class="bi bi-type-underline"></i></button><button type="button" id="insertToken" class="btn btn-outline-primary" title="Inserir campo dinâmico"><i class="bi bi-braces"></i></button></div><textarea id="propText" rows="4" class="form-control form-control-sm"></textarea><div id="richHelp" class="form-text d-none">Insira campos dinâmicos no ponto do cursor.</div></div>
                <div class="row g-2"><div class="col-6"><label class="form-label small">X (mm)</label><input id="propX" type="number" min="0" step="0.1" class="form-control form-control-sm"></div><div class="col-6"><label class="form-label small">Y (mm)</label><input id="propY" type="number" min="0" step="0.1" class="form-control form-control-sm"></div><div class="col-6"><label class="form-label small">Largura (mm)</label><input id="propWidth" type="number" min="1" step="0.1" class="form-control form-control-sm"></div><div class="col-6"><label class="form-label small">Altura (mm)</label><input id="propHeight" type="number" min="1" step="0.1" class="form-control form-control-sm"></div></div>
                <div id="textStyles" class="row g-2 mt-0"><div class="col-8"><label class="form-label small">Família da fonte</label><select id="propFontFamily" class="form-select form-select-sm"></select></div><div class="col-4"><label class="form-label small">Tamanho (pt)</label><input id="propFontSize" type="number" min="1" max="300" step="1" class="form-control form-control-sm"></div><div class="col-6"><label class="form-label small">Cor</label><input id="propColor" type="color" class="form-control form-control-color w-100"></div><div class="col-6"><label class="form-label small">Alinhamento</label><select id="propAlign" class="form-select form-select-sm"><option value="esquerda">Esquerda</option><option value="centralizado">Centralizado</option><option value="direita">Direita</option><option value="justificado">Justificado</option></select></div><div class="col-12"><label class="form-label small d-block">Estilo</label><div class="btn-group w-100" role="group"><input id="propBold" type="checkbox" class="btn-check"><label for="propBold" class="btn btn-sm btn-outline-secondary" title="Negrito"><i class="bi bi-type-bold"></i></label><input id="propItalic" type="checkbox" class="btn-check"><label for="propItalic" class="btn btn-sm btn-outline-secondary" title="Itálico"><i class="bi bi-type-italic"></i></label><input id="propUnderline" type="checkbox" class="btn-check"><label for="propUnderline" class="btn btn-sm btn-outline-secondary" title="Sublinhado"><i class="bi bi-type-underline"></i></label></div></div></div>
            </div>
        </div></aside>
        <section class="builder-canvas-area"><div id="layoutCanvas" class="layout-canvas" style="--ratio:{{ max((int)$template->largura,1) / max((int)$template->altura,1) }};@if($template->backgroundUrl())background-image:url('{{ $template->backgroundUrl() }}')@endif">@unless($template->backgroundUrl())<div class="empty-background"><span><i class="bi bi-image me-1"></i>Template sem imagem de fundo</span></div>@endunless</div></section>
    </form>
</div>
<div class="modal fade" id="testModal" tabindex="-1"><div class="modal-dialog"><form id="testForm" class="modal-content"><div class="modal-header"><h2 class="modal-title h5">Testar template com dados reais</h2><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label">Participante de teste *</label><select name="participante_teste_id" class="form-select" required><option value="">Selecione</option>@foreach($testParticipants as $test)<option value="{{ $test->id }}">{{ $test->participante?->nome }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Atividade</label><select name="atividade_id" class="form-select"><option value="">Sem atividade</option>@foreach($activities as $activity)<option value="{{ $activity->id }}">{{ $activity->nome }}</option>@endforeach</select></div><div><label class="form-label">Responsável</label><select name="responsavel_id" class="form-select"><option value="">Sem responsável</option>@foreach($responsibles as $responsible)<option value="{{ $responsible->id }}">{{ $responsible->participante?->nome }}</option>@endforeach</select></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-success">Gerar teste</button></div></form></div></div>
@endsection
@push('scripts')
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
window.layoutBuilderConfig={width:@json(max((int)$template->largura,1)),height:@json(max((int)$template->altura,1)),elements:@json($template->elementos_layout ?? []),fonts:@json($fonts),sources:@json($dynamicSources),previewUrl:@json(route('templates.builder.preview',$template)),fontUploadUrl:@json(route('templates.builder.fonts.store',$template))};
document.addEventListener('DOMContentLoaded',()=>{
 $('#propLibraryImage').select2({theme:'bootstrap-5',width:'100%',placeholder:'Pesquise uma imagem',allowClear:true});
 $('#propResponsibleSignature').select2({theme:'bootstrap-5',width:'100%',placeholder:'Pesquise uma rubrica ou responsável',allowClear:true});
});
</script>
<script src="{{ asset('template-layout-builder.js') }}?v={{ filemtime(public_path('template-layout-builder.js')) }}"></script>
@endpush
