@extends('layouts.app')
@section('title',$template->exists?'Editar template':'Novo template')
@push('styles')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css" rel="stylesheet">
<style>.background-preview{max-width:100%;max-height:24rem;object-fit:contain}.color-preview{display:block;max-width:100%;width:32rem;border:1px solid #dee2e6;border-radius:.5rem}</style>
@endpush
@section('content')
@php($uploadedExists=$template->uploadedBackgroundExists())
@php($coloredExists=$template->coloredBackgroundExists())
@php($gradientExists=$template->gradientBackgroundExists())
<div class="mb-4"><h1 class="page-title">{{ $template->exists?'Editar template':'Novo template' }}</h1><p class="page-description mb-0">Configure o modelo e sua imagem de fundo.</p></div>
<form method="POST" enctype="multipart/form-data" action="{{ $template->exists?route('templates.update',$template):route('templates.store') }}">@csrf @if($template->exists) @method('PUT') @endif
<div class="card content-card"><div class="card-header"><h2 class="h5 fw-bold mb-0">Dados do template</h2></div><div class="card-body p-4">
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="row g-3">
<div class="col-12 col-md-6"><label for="nome" class="form-label">Nome</label><input id="nome" name="nome" class="form-control" maxlength="100" value="{{ old('nome',$template->nome) }}"></div>
<div class="col-12 col-md-4"><label for="certificado_a1" class="form-label">Certificado A1</label><select id="certificado_a1" name="certificado_a1" class="form-select"><option value=""></option>@if(old('certificado_a1',$template->certificado_a1))<option value="{{ old('certificado_a1',$template->certificado_a1) }}" selected>#{{ $template->certificadoA1?->id ?? old('certificado_a1',$template->certificado_a1) }} · {{ $template->certificadoA1?->nome ?? 'Certificado selecionado' }}</option>@endif</select></div>
<div class="col-12 col-md-2"><label for="ativo" class="form-label">Status *</label><select id="ativo" name="ativo" class="form-select" required><option value="1" @selected((string)old('ativo',$template->exists?(int)$template->ativo:1)==='1')>Ativo</option><option value="0" @selected((string)old('ativo',$template->exists?(int)$template->ativo:1)==='0')>Inativo</option></select></div>
<div class="col-6 col-md-3"><label for="pagina" class="form-label">Página</label><select id="pagina" name="pagina" class="form-select">@foreach(['A4','Carta','Oficio','Personalizado'] as $value)<option value="{{ $value }}" @selected(old('pagina',$template->pagina ?? 'A4')===$value)>{{ $value }}</option>@endforeach</select></div>
<div class="col-6 col-md-3"><label for="layout_pagina" class="form-label">Layout</label><select id="layout_pagina" name="layout_pagina" class="form-select">@foreach(['Retrato','Paisagem'] as $value)<option value="{{ $value }}" @selected(old('layout_pagina',$template->layout_pagina ?? 'Retrato')===$value)>{{ $value }}</option>@endforeach</select></div>
<div id="customDimensions" class="col-12 {{ old('pagina',$template->pagina ?? 'A4')==='Personalizado'?'':'d-none' }}"><div class="row g-3"><div class="col-6 col-md-3"><label for="largura" class="form-label">Largura (mm)</label><input id="largura" name="largura" type="number" min="1" class="form-control" value="{{ old('largura',$template->largura ?? 210) }}"></div><div class="col-6 col-md-3"><label for="altura" class="form-label">Altura (mm)</label><input id="altura" name="altura" type="number" min="1" class="form-control" value="{{ old('altura',$template->altura ?? 297) }}"></div></div></div>

<div class="col-12"><div class="row align-items-end g-2 mb-3"><div class="col-12 col-md-4"><label for="backgroundType" class="form-label">Plano de fundo</label><select id="backgroundType" name="tipo_fundo" class="form-select"><option value="imagem" @selected(old('tipo_fundo',$template->tipo_fundo ?: 'imagem')==='imagem')>Imagem</option><option value="colorido" @selected(old('tipo_fundo',$template->tipo_fundo)==='colorido')>Fundo colorido</option><option value="degrade" @selected(old('tipo_fundo',$template->tipo_fundo)==='degrade')>Fundo degradê</option></select></div></div><input type="hidden" name="fundo_colorido_ativo" value="0">
    <div id="uploadBackground"><input id="fundo" name="fundo" type="file" class="form-control" accept=".png,.jpg,.jpeg,image/png,image/jpeg"><div class="form-text">PNG, JPG ou JPEG, até 10 MB.</div><input id="remover_fundo" name="remover_fundo" type="hidden" value="0">@if($template->fundo&&!$uploadedExists)<div class="alert alert-warning mt-2">O arquivo <strong>{{ $template->fundo }}</strong> não foi encontrado.</div>@endif<div id="uploadPreviewArea" class="mt-3 {{ $uploadedExists?'':'d-none' }}"><img id="uploadPreview" class="background-preview border rounded" @if($uploadedExists) src="{{ asset('certificado/imagem_fundo/'.$template->fundo) }}" @endif alt="Imagem de fundo enviada"><div><button id="removeUpload" type="button" class="btn btn-sm btn-outline-danger mt-2"><i class="bi bi-x-lg me-1"></i>Remover imagem enviada</button></div></div></div>
    <div id="colorBackground" class="d-none"><input id="remover_fundo_colorido" name="remover_fundo_colorido" type="hidden" value="0">@if($coloredExists)<div id="existingColor"><img src="{{ asset('certificado/imagem_fundo/'.$template->fundo_colorido) }}" class="background-preview border rounded" alt="Fundo colorido"><div class="form-text">Cor atual: {{ $template->cor_fundo }}. Para gerar outra cor, remova primeiro este fundo.</div><button id="removeColored" type="button" class="btn btn-sm btn-outline-danger mt-2"><i class="bi bi-x-lg me-1"></i>Remover fundo colorido</button></div>@endif
        <div id="colorPickerArea" class="{{ $coloredExists?'d-none':'' }}"><label for="cor_fundo" class="form-label">Selecionar cor</label><div class="d-flex gap-2"><input id="cor_fundo" name="cor_fundo" type="color" class="form-control form-control-color" value="{{ old('cor_fundo',$template->cor_fundo ?: '#ffffff') }}" @disabled($coloredExists)><input id="colorHex" type="text" class="form-control font-monospace" maxlength="7" pattern="#[0-9A-Fa-f]{6}" value="{{ old('cor_fundo',$template->cor_fundo ?: '#ffffff') }}" aria-label="Código hexadecimal da cor" @disabled($coloredExists) style="max-width:9rem"></div><div class="mt-3"><canvas id="colorPreview" class="color-preview" aria-label="Miniatura do fundo colorido"></canvas></div><div class="form-text">A imagem será gerada automaticamente nas dimensões da página e do layout.</div></div>
    </div>
    <div id="gradientBackground" class="d-none"><input id="remover_fundo_degrade" name="remover_fundo_degrade" type="hidden" value="0">@if($gradientExists)<div id="existingGradient"><img src="{{ asset('certificado/imagem_fundo/'.$template->fundo_degrade) }}" class="background-preview border rounded" alt="Fundo degradê"><div class="form-text">De {{ $template->cor_degrade_inicio }} para {{ $template->cor_degrade_fim }}. Para gerar outro degradê, remova primeiro este fundo.</div><button id="removeGradient" type="button" class="btn btn-sm btn-outline-danger mt-2"><i class="bi bi-x-lg me-1"></i>Remover fundo degradê</button></div>@endif
        <div id="gradientPickerArea" class="{{ $gradientExists?'d-none':'' }}"><div class="d-flex flex-wrap gap-3"><div><label for="gradientStart" class="form-label">Cor inicial</label><input id="gradientStart" name="cor_degrade_inicio" type="color" class="form-control form-control-color" value="{{ old('cor_degrade_inicio',$template->cor_degrade_inicio ?: '#ffffff') }}" @disabled($gradientExists)></div><div><label for="gradientEnd" class="form-label">Cor final</label><input id="gradientEnd" name="cor_degrade_fim" type="color" class="form-control form-control-color" value="{{ old('cor_degrade_fim',$template->cor_degrade_fim ?: '#000000') }}" @disabled($gradientExists)></div><div class="flex-grow-1"><label for="gradientDirection" class="form-label">Orientação</label><select id="gradientDirection" name="direcao_degrade" class="form-select" @disabled($gradientExists)>@foreach(['cima_baixo'=>'Cima → baixo','baixo_cima'=>'Baixo → cima','esquerda_direita'=>'Esquerda → direita','direita_esquerda'=>'Direita → esquerda','superior_esquerdo_inferior_direito'=>'Superior esquerdo → inferior direito','inferior_direito_superior_esquerdo'=>'Inferior direito → superior esquerdo','superior_direito_inferior_esquerdo'=>'Superior direito → inferior esquerdo','inferior_esquerdo_superior_direito'=>'Inferior esquerdo → superior direito'] as $value=>$label)<option value="{{ $value }}" @selected(old('direcao_degrade',$template->direcao_degrade ?: 'cima_baixo')===$value)>{{ $label }}</option>@endforeach</select></div></div><div class="mt-3"><canvas id="gradientPreview" class="color-preview" aria-label="Miniatura do fundo degradê"></canvas></div><div class="form-text">A cor inicial parte do primeiro lado indicado e termina no segundo.</div></div>
    </div>
</div>
</div><div class="d-flex justify-content-end gap-2 mt-4"><a href="{{ route('templates.index') }}" class="btn btn-outline-secondary">Cancelar</a><button class="btn btn-primary"><i class="bi bi-check-lg me-1"></i>Salvar</button></div>
</div></div></form>
@endsection
@push('scripts')
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
document.addEventListener('DOMContentLoaded',()=>{
 $('#certificado_a1').select2({theme:'bootstrap-5',width:'100%',placeholder:'Pesquise por ID ou nome',allowClear:true,ajax:{url:@json(route('templates.certificados-a1',[],false)),dataType:'json',delay:250,data:p=>({q:p.term||'',page:p.page||1}),processResults:r=>r}});
 const pagina=document.getElementById('pagina'),layout=document.getElementById('layout_pagina'),dimensions=document.getElementById('customDimensions'),width=document.getElementById('largura'),height=document.getElementById('altura'),sizes={A4:[210,297],Carta:[216,279],Oficio:[216,356]},backgroundType=document.getElementById('backgroundType'),uploadBox=document.getElementById('uploadBackground'),colorBox=document.getElementById('colorBackground'),gradientBox=document.getElementById('gradientBackground'),color=document.getElementById('cor_fundo'),colorPreview=document.getElementById('colorPreview'),gradientStart=document.getElementById('gradientStart'),gradientEnd=document.getElementById('gradientEnd'),gradientDirection=document.getElementById('gradientDirection'),gradientPreview=document.getElementById('gradientPreview');
 const attachHex=(picker,id,label)=>{let text=document.getElementById(id);if(text)return text;const wrapper=document.createElement('div');wrapper.className='d-flex gap-2';picker.parentNode.insertBefore(wrapper,picker);wrapper.appendChild(picker);text=document.createElement('input');text.id=id;text.type='text';text.className='form-control font-monospace';text.maxLength=7;text.pattern='#[0-9A-Fa-f]{6}';text.value=picker.value.toUpperCase();text.setAttribute('aria-label',label);text.style.width='9rem';text.disabled=picker.disabled;wrapper.appendChild(text);return text};
 const colorHex=attachHex(color,'colorHex','Código hexadecimal da cor'),gradientStartHex=attachHex(gradientStart,'gradientStartHex','Código hexadecimal da cor inicial'),gradientEndHex=attachHex(gradientEnd,'gradientEndHex','Código hexadecimal da cor final');
 const swapContainer=document.createElement('div');swapContainer.className='d-flex align-items-end';const swapColors=document.createElement('button');swapColors.type='button';swapColors.className='btn btn-outline-secondary';swapColors.title='Trocar cores inicial e final';swapColors.setAttribute('aria-label','Trocar cores inicial e final');swapColors.innerHTML='<i class="bi bi-arrow-left-right"></i>';swapContainer.appendChild(swapColors);gradientEnd.closest('.d-flex.flex-wrap')?.insertBefore(swapContainer,gradientEnd.parentElement.nextElementSibling);
 swapColors.disabled=gradientStart.disabled;
 const drawColor=()=>{if(!color||!colorPreview)return;colorPreview.width=Math.max(Number(width.value)||210,1);colorPreview.height=Math.max(Number(height.value)||297,1);const context=colorPreview.getContext('2d');context.fillStyle=color.value;context.fillRect(0,0,colorPreview.width,colorPreview.height)};
 const drawGradient=()=>{if(!gradientStart||!gradientEnd||!gradientPreview)return;gradientPreview.width=Math.max(Number(width.value)||210,1);gradientPreview.height=Math.max(Number(height.value)||297,1);const w=gradientPreview.width,h=gradientPreview.height,points={cima_baixo:[0,0,0,h],baixo_cima:[0,h,0,0],esquerda_direita:[0,0,w,0],direita_esquerda:[w,0,0,0],superior_esquerdo_inferior_direito:[0,0,w,h],inferior_direito_superior_esquerdo:[w,h,0,0],superior_direito_inferior_esquerdo:[w,0,0,h],inferior_esquerdo_superior_direito:[0,h,w,0]},context=gradientPreview.getContext('2d'),gradient=context.createLinearGradient(...(points[gradientDirection?.value]||points.cima_baixo));gradient.addColorStop(0,gradientStart.value);gradient.addColorStop(1,gradientEnd.value);context.fillStyle=gradient;context.fillRect(0,0,w,h)};
 const bindHex=(picker,text,redraw)=>{picker.addEventListener('input',()=>{text.value=picker.value.toUpperCase();text.classList.remove('is-invalid');redraw()});text.addEventListener('input',()=>{let value=text.value.trim();if(/^[0-9a-fA-F]{6}$/.test(value))value='#'+value;if(/^#[0-9a-fA-F]{6}$/.test(value)){picker.value=value;text.value=value.toUpperCase();text.classList.remove('is-invalid');redraw()}});text.addEventListener('blur',()=>text.classList.toggle('is-invalid',!/^#[0-9a-fA-F]{6}$/.test(text.value)))};
 bindHex(color,colorHex,drawColor);bindHex(gradientStart,gradientStartHex,drawGradient);bindHex(gradientEnd,gradientEndHex,drawGradient);
 swapColors.addEventListener('click',()=>{const start=gradientStart.value;gradientStart.value=gradientEnd.value;gradientEnd.value=start;gradientStartHex.value=gradientStart.value.toUpperCase();gradientEndHex.value=gradientEnd.value.toUpperCase();gradientStartHex.classList.remove('is-invalid');gradientEndHex.classList.remove('is-invalid');drawGradient()});
 const updateDimensions=()=>{const custom=pagina.value==='Personalizado';dimensions.classList.toggle('d-none',!custom);if(!custom&&sizes[pagina.value]){const [w,h]=sizes[pagina.value],landscape=layout.value==='Paisagem';width.value=landscape?h:w;height.value=landscape?w:h}else if(custom&&(!width.value||!height.value)){width.value=layout.value==='Paisagem'?297:210;height.value=layout.value==='Paisagem'?210:297}drawColor();drawGradient()};
 const updateBackgroundType=()=>{uploadBox.classList.toggle('d-none',backgroundType.value!=='imagem');colorBox.classList.toggle('d-none',backgroundType.value!=='colorido');gradientBox.classList.toggle('d-none',backgroundType.value!=='degrade')};pagina.addEventListener('change',updateDimensions);layout.addEventListener('change',updateDimensions);width.addEventListener('input',()=>{drawColor();drawGradient()});height.addEventListener('input',()=>{drawColor();drawGradient()});backgroundType.addEventListener('change',updateBackgroundType);if(color)color.addEventListener('input',drawColor);if(gradientStart)gradientStart.addEventListener('input',drawGradient);if(gradientEnd)gradientEnd.addEventListener('input',drawGradient);if(gradientDirection)gradientDirection.addEventListener('change',drawGradient);updateDimensions();updateBackgroundType();drawColor();drawGradient();
 const input=document.getElementById('fundo'),uploadArea=document.getElementById('uploadPreviewArea'),preview=document.getElementById('uploadPreview'),uploadFlag=document.getElementById('remover_fundo');let url=null;input.addEventListener('change',()=>{const file=input.files[0];if(!file)return;if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(file);preview.src=url;uploadArea.classList.remove('d-none');uploadFlag.value='0'});document.getElementById('removeUpload').addEventListener('click',()=>{if(url)URL.revokeObjectURL(url);url=null;input.value='';preview.removeAttribute('src');uploadArea.classList.add('d-none');uploadFlag.value='1'});
 const removeColored=document.getElementById('removeColored');if(removeColored)removeColored.addEventListener('click',()=>{document.getElementById('remover_fundo_colorido').value='1';document.getElementById('existingColor').classList.add('d-none');document.getElementById('colorPickerArea').classList.remove('d-none');color.disabled=false;colorHex.disabled=false;drawColor()});
 const removeGradient=document.getElementById('removeGradient');if(removeGradient)removeGradient.addEventListener('click',()=>{document.getElementById('remover_fundo_degrade').value='1';document.getElementById('existingGradient').classList.add('d-none');document.getElementById('gradientPickerArea').classList.remove('d-none');gradientStart.disabled=false;gradientEnd.disabled=false;gradientStartHex.disabled=false;gradientEndHex.disabled=false;gradientDirection.disabled=false;swapColors.disabled=false;drawGradient()});
});
</script>
@endpush
