@extends('layouts.app')
@section('title',$template->exists?'Editar template':'Novo template')
@push('styles')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css" rel="stylesheet">
<style>.background-preview{max-width:100%;max-height:24rem;object-fit:contain}.color-preview{display:block;max-width:100%;width:32rem;border:1px solid #dee2e6;border-radius:.5rem}</style>
@endpush
@section('content')
@php($uploadedExists=$template->uploadedBackgroundExists())
@php($coloredExists=$template->coloredBackgroundExists())
<div class="mb-4"><h1 class="page-title">{{ $template->exists?'Editar template':'Novo template' }}</h1><p class="page-description mb-0">Configure o modelo e sua imagem de fundo.</p></div>
<form method="POST" enctype="multipart/form-data" action="{{ $template->exists?route('templates.update',$template):route('templates.store') }}">@csrf @if($template->exists) @method('PUT') @endif
<div class="card content-card"><div class="card-header"><h2 class="h5 fw-bold mb-0">Dados do template</h2></div><div class="card-body p-4">
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="row g-3">
<div class="col-12 col-md-6"><label for="nome" class="form-label">Nome</label><input id="nome" name="nome" class="form-control" maxlength="100" value="{{ old('nome',$template->nome) }}"></div>
<div class="col-12 col-md-4"><label for="certificado_a1" class="form-label">Certificado A1</label><select id="certificado_a1" name="certificado_a1" class="form-select"><option value=""></option>@if(old('certificado_a1',$template->certificado_a1))<option value="{{ old('certificado_a1',$template->certificado_a1) }}" selected>#{{ $template->certificadoA1?->id ?? old('certificado_a1',$template->certificado_a1) }} · {{ $template->certificadoA1?->nome ?? 'Certificado selecionado' }}</option>@endif</select></div>
<div class="col-12 col-md-2"><label for="ativo" class="form-label">Status *</label><select id="ativo" name="ativo" class="form-select" required><option value="1" @selected((string)old('ativo',$template->exists?(int)$template->ativo:1)==='1')>Ativo</option><option value="0" @selected((string)old('ativo',$template->exists?(int)$template->ativo:1)==='0')>Inativo</option></select></div>
<div class="col-6 col-md-3"><label for="pagina" class="form-label">Página</label><select id="pagina" name="pagina" class="form-select">@foreach(['A4','Carta','Oficio','Personalizado'] as $value)<option value="{{ $value }}" @selected(old('pagina',$template->pagina ?? 'A4')===$value)>{{ $value }}</option>@endforeach</select></div>
<div class="col-6 col-md-3"><label for="layout_pagina" class="form-label">Layout</label><select id="layout_pagina" name="layout_pagina" class="form-select">@foreach(['Retrato','Paisagem'] as $value)<option value="{{ $value }}" @selected(old('layout_pagina',$template->layout_pagina ?? 'Retrato')===$value)>{{ $value }}</option>@endforeach</select></div>
<div id="customDimensions" class="col-12 {{ old('pagina',$template->pagina ?? 'A4')==='Personalizado'?'':'d-none' }}"><div class="row g-3"><div class="col-6 col-md-3"><label for="largura" class="form-label">Largura (mm)</label><input id="largura" name="largura" type="number" min="1" class="form-control" value="{{ old('largura',$template->largura ?? 210) }}"></div><div class="col-6 col-md-3"><label for="altura" class="form-label">Altura (mm)</label><input id="altura" name="altura" type="number" min="1" class="form-control" value="{{ old('altura',$template->altura ?? 297) }}"></div></div></div>

<div class="col-12"><div class="d-flex align-items-center gap-3 mb-2"><label class="form-label mb-0">Plano de fundo</label><div class="form-check form-switch mb-0"><input type="hidden" name="fundo_colorido_ativo" value="0"><input id="coloredBackground" name="fundo_colorido_ativo" value="1" type="checkbox" class="form-check-input" @checked((bool)old('fundo_colorido_ativo',$template->fundo_colorido_ativo))><label for="coloredBackground" class="form-check-label">Colorido</label></div></div>
    <div id="uploadBackground"><input id="fundo" name="fundo" type="file" class="form-control" accept=".png,.jpg,.jpeg,image/png,image/jpeg"><div class="form-text">PNG, JPG ou JPEG, até 10 MB.</div><input id="remover_fundo" name="remover_fundo" type="hidden" value="0">@if($template->fundo&&!$uploadedExists)<div class="alert alert-warning mt-2">O arquivo <strong>{{ $template->fundo }}</strong> não foi encontrado.</div>@endif<div id="uploadPreviewArea" class="mt-3 {{ $uploadedExists?'':'d-none' }}"><img id="uploadPreview" class="background-preview border rounded" @if($uploadedExists) src="{{ asset('certificado/imagem_fundo/'.$template->fundo) }}" @endif alt="Imagem de fundo enviada"><div><button id="removeUpload" type="button" class="btn btn-sm btn-outline-danger mt-2"><i class="bi bi-x-lg me-1"></i>Remover imagem enviada</button></div></div></div>
    <div id="colorBackground" class="d-none"><input id="remover_fundo_colorido" name="remover_fundo_colorido" type="hidden" value="0">@if($coloredExists)<div id="existingColor"><img src="{{ asset('certificado/imagem_fundo/'.$template->fundo_colorido) }}" class="background-preview border rounded" alt="Fundo colorido"><div class="form-text">Cor atual: {{ $template->cor_fundo }}. Para gerar outra cor, remova primeiro este fundo.</div><button id="removeColored" type="button" class="btn btn-sm btn-outline-danger mt-2"><i class="bi bi-x-lg me-1"></i>Remover fundo colorido</button></div>@endif
        <div id="colorPickerArea" class="{{ $coloredExists?'d-none':'' }}"><label for="cor_fundo" class="form-label">Selecionar cor</label><input id="cor_fundo" name="cor_fundo" type="color" class="form-control form-control-color" value="{{ old('cor_fundo',$template->cor_fundo ?: '#ffffff') }}" @disabled($coloredExists)><div class="mt-3"><canvas id="colorPreview" class="color-preview" aria-label="Miniatura do fundo colorido"></canvas></div><div class="form-text">A imagem será gerada automaticamente nas dimensões da página e do layout.</div></div>
    </div>
</div>
</div><div class="d-flex justify-content-end gap-2 mt-4"><a href="{{ route('templates.index') }}" class="btn btn-outline-secondary">Cancelar</a><button class="btn btn-primary"><i class="bi bi-check-lg me-1"></i>Salvar</button></div>
</div></div></form>
@endsection
@push('scripts')
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
document.addEventListener('DOMContentLoaded',()=>{
 $('#certificado_a1').select2({theme:'bootstrap-5',width:'100%',placeholder:'Pesquise por ID ou nome',allowClear:true,ajax:{url:@json(route('templates.certificados-a1',[],false)),dataType:'json',delay:250,data:p=>({q:p.term||'',page:p.page||1}),processResults:r=>r}});
 const pagina=document.getElementById('pagina'),layout=document.getElementById('layout_pagina'),dimensions=document.getElementById('customDimensions'),width=document.getElementById('largura'),height=document.getElementById('altura'),sizes={A4:[210,297],Carta:[216,279],Oficio:[216,356]},colored=document.getElementById('coloredBackground'),uploadBox=document.getElementById('uploadBackground'),colorBox=document.getElementById('colorBackground'),color=document.getElementById('cor_fundo'),colorPreview=document.getElementById('colorPreview');
 const drawColor=()=>{if(!color||!colorPreview)return;colorPreview.width=Math.max(Number(width.value)||210,1);colorPreview.height=Math.max(Number(height.value)||297,1);const context=colorPreview.getContext('2d');context.fillStyle=color.value;context.fillRect(0,0,colorPreview.width,colorPreview.height)};
 const updateDimensions=()=>{const custom=pagina.value==='Personalizado';dimensions.classList.toggle('d-none',!custom);if(!custom&&sizes[pagina.value]){const [w,h]=sizes[pagina.value],landscape=layout.value==='Paisagem';width.value=landscape?h:w;height.value=landscape?w:h}else if(custom&&(!width.value||!height.value)){width.value=layout.value==='Paisagem'?297:210;height.value=layout.value==='Paisagem'?210:297}drawColor()};
 const updateBackgroundType=()=>{uploadBox.classList.toggle('d-none',colored.checked);colorBox.classList.toggle('d-none',!colored.checked)};pagina.addEventListener('change',updateDimensions);layout.addEventListener('change',updateDimensions);width.addEventListener('input',drawColor);height.addEventListener('input',drawColor);colored.addEventListener('change',updateBackgroundType);if(color)color.addEventListener('input',drawColor);updateDimensions();updateBackgroundType();drawColor();
 const input=document.getElementById('fundo'),uploadArea=document.getElementById('uploadPreviewArea'),preview=document.getElementById('uploadPreview'),uploadFlag=document.getElementById('remover_fundo');let url=null;input.addEventListener('change',()=>{const file=input.files[0];if(!file)return;if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(file);preview.src=url;uploadArea.classList.remove('d-none');uploadFlag.value='0'});document.getElementById('removeUpload').addEventListener('click',()=>{if(url)URL.revokeObjectURL(url);url=null;input.value='';preview.removeAttribute('src');uploadArea.classList.add('d-none');uploadFlag.value='1'});
 const removeColored=document.getElementById('removeColored');if(removeColored)removeColored.addEventListener('click',()=>{document.getElementById('remover_fundo_colorido').value='1';document.getElementById('existingColor').classList.add('d-none');document.getElementById('colorPickerArea').classList.remove('d-none');color.disabled=false;drawColor()});
});
</script>
@endpush
